- name: Disable Default Nginx
  ansible.builtin.shell: dnf module disable nginx -y; dnf module enable nginx:1.24 -y

- name: Install Nginx
  ansible.builtin.dnf:
    name: nginx
    state: present

- name: Copy Nginx Config File
  ansible.builtin.copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: Remove default content
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: Create Nginx content directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

- name: Download and extract Frontend content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: Start Nginx Service
  ansible.builtin.systemd_service:
    state: started
    name: nginx
    enabled: true