- name: Install NodeJS
  ansible.builtin.include_role:
    name: common
    task_from: nodejs

- name: Run systemd service
  ansible.builtin.include_role:
    name: common
    tasks_from: systemd_setup