- name: Add Application User
  ansible.builtin.user:
    name: roboshop

- name: Delete Old Application Directory
  ansible.builtin.file:
    src: /app
    state: absent

- name: Create Application Directory
  ansible.builtin.file:
    src: /app
    state: present

- name: Download and Extract Application Content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/{{ component_name }}-v3.zip
    dest: /app
    remote_src: true