- name: Install Maven
  ansible.builtin.dnf:
    name: maven
    state: present

- name: Load Pre App Setup Prerequisites
  ansible.builtin.include_tasks:
    name: app_pre_setup.yml

- name: Download App Dependencies
  ansible.builtin.shell: mvn clean package; mv target/{{ component_name }}-1.0.jar {{ component_name }}.jar
  args:
    chdir: /app
