- name: Setup Docker
  ansible.builtin.include_role:
    name: common
    tasks_from: docker

- name: Run user container
  community.docker.docker_container:
    name: user
    image: public.ecr.aws/w8x4g9h7/roboshop-v3/user
    state: started
    ports:
      - "8080:8080"
    env:
      MONGO_URL: "mongodb://mongodb-dev.vdevops.io:27017/users"
      MONGO: "true"
      REDIS_URL: "redis://redis-dev.vdevops.io:6379"