- name: Setup Docker
  ansible.builtin.include_role:
    name: common
    tasks_from: docker

- name: Run payment container
  community.docker.docker_container:
    name: payment
    image: public.ecr.aws/w8x4g9h7/roboshop-v3/payment
    state: started
    ports:
      - "8080:8080"
    env:
      CART_HOST: "cart-dev.vdevops.io"
      CART_PORT: 8080
      USER_HOST: "user-dev.vdevops.io"
      USER_PORT: 8080
      AMQP_HOST: "rabbitmq-dev.vdevops.io"
      AMQP_USER: "roboshop"
      AMQP_PASS: "roboshop123"